### ISSUE TITLE
[Bug] "Failed to load the native TensorFlow runtime."

### ISSUE THREAD

**Issue by HansHermann123** [deezer/spleeter#142]
## Description

running spleeter produces a "Failed to load the native TensorFlow runtime".

## Step to reproduce

1. On Windows 7 64 bit, installed Python 3.7.5, installed Spleeter using pip in an administrator shell. Installation runs fine without errors.
2. run spleeter as administrator using command line
3.  produces "Failed to load the native TensorFlow runtime" error (despite it was installed successfully according to install output).

## Output

Traceback (most recent call last):
  File "c:\users\User\appdata\local\programs\python\python37\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "c:\users\User\appdata\local\programs\python\python37\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "c:\users\User\appdata\local\programs\python\python37\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_hel
per
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "c:\users\User\appdata\local\programs\python\python37\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "c:\users\User\appdata\local\programs\python\python37\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed with error code 3221225501

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\User\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\User\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\Scripts\spleeter.exe\__main__.py", line 7, in <module>
  File "c:\users\User\appdata\local\programs\python\python37\lib\site-packages\spleeter\__main__.py", line 54, in entrypoint
    main(sys.argv)
  File "c:\users\User\appdata\local\programs\python\python37\lib\site-packages\spleeter\__main__.py", line 36, in main
    enable_logging()
  File "c:\users\User\appdata\local\programs\python\python37\lib\site-packages\spleeter\utils\logging.py", line 60, in enable_logging
    tf_logger = get_tensorflow_logger()
  File "c:\users\User\appdata\local\programs\python\python37\lib\site-packages\spleeter\utils\logging.py", line 27, in get_tensorflow_logger
    from tensorflow.compat.v1 import logging
  File "c:\users\User\appdata\local\programs\python\python37\lib\site-packages\tensorflow\__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "c:\users\User\appdata\local\programs\python\python37\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "c:\users\User\appdata\local\programs\python\python37\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "c:\users\User\appdata\local\programs\python\python37\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "c:\users\User\appdata\local\programs\python\python37\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "c:\users\User\appdata\local\programs\python\python37\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_hel
per
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "c:\users\User\appdata\local\programs\python\python37\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "c:\users\User\appdata\local\programs\python\python37\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed with error code 3221225501

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

## Environment

|                   |                                 |
| ----------------- | ------------------------------- |
| OS                | Windows  |
| Installation type |  pip             |
| RAM available     | 16GB                             |
| Hardware spec     | Radeon HD5550 / AMD PhenomIIX61090              |

**Comment by AlexMifs** [comment]
I am having same error with tensorflow on both raspbian and windows. Seems there is something wrong with the version

**Comment by Faylixe** [comment]
Did you try to installed `spleeter` or `spleeter-gpu` ?

**Comment by HansHermann123** [comment]
I tried spleeter.

**Comment by richiecannizzo** [comment]
i get the same error after i installed gpu version. tried uninstalling all and installing just normal spleeter again but error remains. :(

**Comment by richiecannizzo** [comment]
FIXED: deleted the spleeter dirs in C:\Users\XXXXX\Miniconda3\Lib\site-packages

**Comment by richiecannizzo** [comment]
FIXED: deleted the spleeter dirs in C:\Users\XXXXX\Miniconda3\Lib\site-packages

and then re pip install spleeter

**Comment by HansHermann123** [comment]
This path does not work for me as I am not using Miniconda. But I tried deleting the spleeter and tensorflow dirs from "C:\Program Files\Python37\Lib\site-packages", then reinstalled spleeter. But it still does not work.

**Comment by Caserol23** [comment]
i had a same problem but throws a error code, not kind like that

`ImportError: DLL load failed with error code -1073741795`
